### PR TITLE
Fix out of bounds draw of last menu item(s)

### PR DESCRIPTION
**Pull request by gaaf**
# What does this implement/fix?

Fix out of bounds draw of last menu item(s)

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

### CODE REVIEW

**Comment by MrMDavidson** [comment]
Hey @gaaf , are you able to provide a screenshot or something of what this is fixing?

**Comment by gaaf** [comment]
Someone already explained in your PR.

https://github.com/esphome/esphome/pull/4105#issuecomment-1679542106

**Comment by MrMDavidson** [comment]
Unfortunately the update to pillow in dev is preventing me from testing this. On my test setup I draw the same menu at different sizes specifically to test things like this. Are you able to validate on your setup what this looks like if the height of the menu is less than an item's height?

**Comment by gaaf** [comment]
> Are you able to validate on your setup what this looks like if the height of the menu is less than an item's height?

There won't be an item drawn. Why would one want to do that? If that needs to be supported, number_items_fit_to_screen should be 1 for that case. In case no item fully fits, this variable is 0 and the code takes the path for multiple items, so it is already wrong.

The original code subtracts the padding from the item's height instead of adding to it. This resulted in a calculated remaining height which is n-times the padding height too low, so that was obviously wrong. The patch fixes that.

All-in-all, the code doesn't properly support partially drawn items. The fact that it did it before is an (unintentional) result of a wrong calculation.

**Comment by MrMDavidson** [comment]
Alright, got my install working - if anyone needs to do so you'll need to install the Dev version of the ESPHome addon when testing.

> > Are you able to validate on your setup what this looks like if the height of the menu is less than an item's height?
> 
> There won't be an item drawn. Why would one want to do that? If that needs to be supported, number_items_fit_to_screen should be 1 for that case. In case no item fully fits, this variable is 0 and the code takes the path for multiple items, so it is already wrong.
> 
> The original code subtracts the padding from the item's height instead of adding to it. This resulted in a calculated remaining height which is n-times the padding height too low, so that was obviously wrong. The patch fixes that.
> 
> All-in-all, the code doesn't properly support partially drawn items. The fact that it did it before is an (unintentional) result of a wrong calculation.

My setup has a menu with multiple items (5 in this case). I don't believe the type of the menu items will impact things - my test is with some labels, some switches, and some submenus I was using for a prior test. For the purposes of this test I've set my font size to be 10px. I've then also edited the padding size to be 5px. My device then renders the menu at 4 different sizes; 
1. Smaller than a a single menu item
2. One and a bit menu items
3. Multiple menu items
4. Lots more menu items (this one is redundant and a hold over from prior testing, whoops)

Then in my render lambda I'm rendering a horizontal line every 5 pixels, drawing a box _around_ each of the menus, and then rendering the menus. See below

```yaml
display:
  playform: ...
  pages:
    - id: test
      lambda: |-
          const auto width = it.get_width();
          const auto height = it.get_height();

          for (int i = 0; i < height; i+= 5) {
            it.horizontal_line(0, i, width);
          }

          it.rectangle(4, 4, 52, 13);
          it.filled_rectangle(5, 5, 50, 10, COLOR_OFF);
          it.menu(5, 5, id(configuration_menu), 50, 10);

          it.rectangle(64, 4, 52, 33);
          it.filled_rectangle(65, 5, 50, 30, COLOR_OFF);
          it.menu(65, 5, id(configuration_menu), 50, 30);

          it.rectangle(124, 4, 52, 73);
          it.filled_rectangle(125, 5, 50, 70, COLOR_OFF);
          it.menu(125, 5, id(configuration_menu), 50, 70);

          it.rectangle(184, 4, 52, height - 2);
          it.filled_rectangle(185, 5, 50, height - 5, COLOR_OFF);
          it.menu(185, 4, id(configuration_menu), 50, height - 5);

          it.filled_rectangle(0, height - 20, 120, 20, COLOR_OFF);
          it.print(0, height - 20, id(small_font), COLOR_ON, TextAlign::TOP_LEFT, "Title of the text here");
```

The purpose of the horizontal lines is to give an aid for counting / guesstimating pixels. I've then installed it on my device with three different versions;

1. The code base this PR is against (with padding set to 5px)
P_20231204_223218

2. This PR (with padding set to 5px)
P_20231204_223549

3. This PR but with Line 135 changes to be less-than-or-equal-to 1 item (and 5px padding)
P_20231204_224011

I agree that the logic this PR fixes is incorrect but I'm not seeing the behaviour you're attempting to fix with this PR. If I'm understanding you correctly I'd expect each menu item to get further and further apart as the index of the menu item increases?

This PR + the equality change [at line 135](https://github.com/MrMDavidson/esphome/pull/125/files#diff-a6e71676880671c672b699cd453c7a7c14269d47994165c44e14b8941cbd0743L135) seems to be more correct. But think there's more work to be done on partial drawing scenarios (the original intent of which was to give an indicator to the user there's more items and to scroll).

Thoughts?

**Comment by gaaf** [comment]
> I agree that the logic this PR fixes is incorrect but I'm not seeing the behaviour you're attempting to fix with this PR. If I'm understanding you correctly I'd expect each menu item to get further and further apart as the index of the menu item increases?

The problem is that due to the miscalculated remaining height, it thinks the height is greater than the actual height and the scrolling goes wrong. You'll only see the issue if there are more items than fit within the bounds *and* you scroll to an item which is initially outside the bounds, the last item for example. Your photo's don't show the problem as you have the first item selected in all cases. See the original report here: https://github.com/esphome/esphome/pull/4105#issuecomment-1679542106.

> This PR + the equality change [at line 135](https://github.com/MrMDavidson/esphome/pull/125/files#diff-a6e71676880671c672b699cd453c7a7c14269d47994165c44e14b8941cbd0743L135) seems to be more correct. But think there's more work to be done on partial drawing scenarios.

I agree that more work is to be done. And when the partial items are rendered correctly, then the special case for a single item isn't necessary anymore.

**Comment by MrMDavidson** [comment]
> > I agree that the logic this PR fixes is incorrect but I'm not seeing the behaviour you're attempting to fix with this PR. If I'm understanding you correctly I'd expect each menu item to get further and further apart as the index of the menu item increases?
> 
> The problem is that due to the miscalculated remaining height, it thinks the height is greater than the actual height and the scrolling goes wrong. You'll only see the issue if there are more items than fit within the bounds _and_ you scroll to an item which is initially outside the bounds, the last item for example. Your photo's don't show the problem as you have the first item selected in all cases. See the original report here: [esphome#4105 (comment)](https://github.com/esphome/esphome/pull/4105#issuecomment-1679542106).

Ah, gotcha, able to repro now. Can confirm this fixes that particular issue!

**Review by MrMDavidson — APPROVED** [review]

**Comment by gaaf** [comment]
I added PR #142 for fixing the remaining issues with scrolling and partial visible items.

**Pull request merged**
